
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ANDAND ARROW AS ASIGNAR ASIGNATION_TYPE ASYNC AWAIT BRACKETL BRACKETR BREAK B_FALSE B_TRUE COMMA CONST CONTAINS_SLICE CONTIN CRATE CURLYL CURLYR DATATYPES DIFFERENT DIVISION DOLLAR DOT DOTDOTDOT DYN ELSE ENDLINE ENUM EQUAL ERRORPROP EXTERN FOR FUNCTION GET_SLICE GREATEQ GREATER HASHSET IF IMPL IN INSERT_HASH LESSEQ LESST LET LOOP LPAREN MAS MATCH MAYOR MAYORIGUAL MENOS MINUSEQ MOD MODULO MOVE MULT MUT NEWFUNC NOT NUMBER NUMDATATYPES OR OROR PATHSEP PLUSEQ POP_VEC PRINT PRINTS PUB PUSH_VEC REF RETURN RPAREN SELF SELFLOWERCASE SLASHEQ STAREQ STATIC STRING STRUCT SUPER TRAIT TYPE U8 UNION_HASH UNSAFE USE VARIABLE VECTOR WHERE WHILE\n    rust : asignacion\n         | prints\n         | hashset\n         | hashfunc\n    \n    asignacion : declarador ASIGNAR expresion ENDLINE\n                | other_operators ENDLINE\n    \n    other_operators : VARIABLE oper_asig expresion\n    \n    declarador : VARIABLE\n                | let_asig\n    \n    let_asig : LET var_tipo\n             | LET MUT var_tipo\n    \n    var_tipo : VARIABLE\n             | VARIABLE  ASIGNATION_TYPE tipos\n    \n    tipos : DATATYPES\n            | NUMDATATYPES\n    \n    oper_asig : ASIGNAR\n                | PLUSEQ\n                | MINUSEQ\n                | STAREQ\n                | SLASHEQ\n    \n    expresion : STRING\n                | U8\n    \n    prints : PRINTS LPAREN print_expresion RPAREN ENDLINE\n    \n    print_expresion : STRING\n                    | STRING COMMA print_args\n    \n    print_args : print_datos COMMA print_args \n                | print_datos\n    \n    print_datos : expresion\n    \n    hashset : LET MUT VARIABLE ASIGNAR HASHSET PATHSEP NEWFUNC ENDLINE\n    \n    hashfunc : hashset_insert\n            | hashset_union\n    \n    hashset_insert : VARIABLE DOT INSERT_HASH LPAREN expresion RPAREN ENDLINE\n    \n    hashset_union : VARIABLE DOT UNION_HASH LPAREN AND VARIABLE RPAREN ENDLINE\n    '
    
_lr_action_items = {'PRINTS':([0,],[8,]),'LET':([0,],[9,]),'VARIABLE':([0,9,17,53,],[10,18,32,57,]),'$end':([1,2,3,4,5,11,12,15,38,47,60,62,63,],[0,-1,-2,-3,-4,-30,-31,-6,-5,-23,-32,-29,-33,]),'ASIGNAR':([6,10,13,18,19,32,33,42,43,44,],[14,22,-9,-12,-10,41,-11,-13,-14,-15,]),'ENDLINE':([7,27,28,29,35,39,56,59,61,],[15,38,-21,-22,-7,47,60,62,63,]),'LPAREN':([8,36,37,],[16,45,46,]),'MUT':([9,],[17,]),'DOT':([10,],[21,]),'PLUSEQ':([10,],[23,]),'MINUSEQ':([10,],[24,]),'STAREQ':([10,],[25,]),'SLASHEQ':([10,],[26,]),'STRING':([14,16,20,22,23,24,25,26,40,45,54,],[28,31,28,-16,-17,-18,-19,-20,28,28,28,]),'U8':([14,20,22,23,24,25,26,40,45,54,],[29,29,-16,-17,-18,-19,-20,29,29,29,]),'ASIGNATION_TYPE':([18,32,],[34,34,]),'INSERT_HASH':([21,],[36,]),'UNION_HASH':([21,],[37,]),'COMMA':([28,29,31,49,50,],[-21,-22,40,54,-28,]),'RPAREN':([28,29,30,31,48,49,50,52,57,58,],[-21,-22,39,-24,-25,-27,-28,56,61,-26,]),'DATATYPES':([34,],[43,]),'NUMDATATYPES':([34,],[44,]),'HASHSET':([41,],[51,]),'AND':([46,],[53,]),'PATHSEP':([51,],[55,]),'NEWFUNC':([55,],[59,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'rust':([0,],[1,]),'asignacion':([0,],[2,]),'prints':([0,],[3,]),'hashset':([0,],[4,]),'hashfunc':([0,],[5,]),'declarador':([0,],[6,]),'other_operators':([0,],[7,]),'hashset_insert':([0,],[11,]),'hashset_union':([0,],[12,]),'let_asig':([0,],[13,]),'var_tipo':([9,17,],[19,33,]),'oper_asig':([10,],[20,]),'expresion':([14,20,40,45,54,],[27,35,50,52,50,]),'print_expresion':([16,],[30,]),'tipos':([34,],[42,]),'print_args':([40,54,],[48,58,]),'print_datos':([40,54,],[49,49,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> rust","S'",1,None,None,None),
  ('rust -> asignacion','rust',1,'p_rust','sintactico.py',14),
  ('rust -> prints','rust',1,'p_rust','sintactico.py',15),
  ('rust -> hashset','rust',1,'p_rust','sintactico.py',16),
  ('rust -> hashfunc','rust',1,'p_rust','sintactico.py',17),
  ('asignacion -> declarador ASIGNAR expresion ENDLINE','asignacion',4,'p_asignacion','sintactico.py',22),
  ('asignacion -> other_operators ENDLINE','asignacion',2,'p_asignacion','sintactico.py',23),
  ('other_operators -> VARIABLE oper_asig expresion','other_operators',3,'p_other_operators','sintactico.py',28),
  ('declarador -> VARIABLE','declarador',1,'p_declarador','sintactico.py',33),
  ('declarador -> let_asig','declarador',1,'p_declarador','sintactico.py',34),
  ('let_asig -> LET var_tipo','let_asig',2,'p_let_asig','sintactico.py',39),
  ('let_asig -> LET MUT var_tipo','let_asig',3,'p_let_asig','sintactico.py',40),
  ('var_tipo -> VARIABLE','var_tipo',1,'p_var_tipo','sintactico.py',45),
  ('var_tipo -> VARIABLE ASIGNATION_TYPE tipos','var_tipo',3,'p_var_tipo','sintactico.py',46),
  ('tipos -> DATATYPES','tipos',1,'p_tipos','sintactico.py',51),
  ('tipos -> NUMDATATYPES','tipos',1,'p_tipos','sintactico.py',52),
  ('oper_asig -> ASIGNAR','oper_asig',1,'p_oper_asig','sintactico.py',57),
  ('oper_asig -> PLUSEQ','oper_asig',1,'p_oper_asig','sintactico.py',58),
  ('oper_asig -> MINUSEQ','oper_asig',1,'p_oper_asig','sintactico.py',59),
  ('oper_asig -> STAREQ','oper_asig',1,'p_oper_asig','sintactico.py',60),
  ('oper_asig -> SLASHEQ','oper_asig',1,'p_oper_asig','sintactico.py',61),
  ('expresion -> STRING','expresion',1,'p_expresion','sintactico.py',66),
  ('expresion -> U8','expresion',1,'p_expresion','sintactico.py',67),
  ('prints -> PRINTS LPAREN print_expresion RPAREN ENDLINE','prints',5,'p_prints','sintactico.py',72),
  ('print_expresion -> STRING','print_expresion',1,'p_print_expresion','sintactico.py',77),
  ('print_expresion -> STRING COMMA print_args','print_expresion',3,'p_print_expresion','sintactico.py',78),
  ('print_args -> print_datos COMMA print_args','print_args',3,'p_print_args','sintactico.py',83),
  ('print_args -> print_datos','print_args',1,'p_print_args','sintactico.py',84),
  ('print_datos -> expresion','print_datos',1,'p_print_datos','sintactico.py',89),
  ('hashset -> LET MUT VARIABLE ASIGNAR HASHSET PATHSEP NEWFUNC ENDLINE','hashset',8,'p_hashset','sintactico.py',94),
  ('hashfunc -> hashset_insert','hashfunc',1,'p_hashfunc','sintactico.py',98),
  ('hashfunc -> hashset_union','hashfunc',1,'p_hashfunc','sintactico.py',99),
  ('hashset_insert -> VARIABLE DOT INSERT_HASH LPAREN expresion RPAREN ENDLINE','hashset_insert',7,'p_hashset_insert','sintactico.py',104),
  ('hashset_union -> VARIABLE DOT UNION_HASH LPAREN AND VARIABLE RPAREN ENDLINE','hashset_union',8,'p_hashset_union','sintactico.py',109),
]
